/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.model.Users;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class signuppage extends javax.swing.JFrame {

    /**
     * Creates new form signuppage
     */
    public signuppage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back2login = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        pw_txtfield = new javax.swing.JPasswordField();
        un_txtfield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        newUN = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back2login.setText("Back to Login");
        back2login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back2loginMouseEntered(evt);
            }
        });
        getContentPane().add(back2login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 290, 40));

        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CA-button.png"))); // NOI18N
        signup.setBorder(null);
        signup.setContentAreaFilled(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 230, 80));

        pw_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_txtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(pw_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 820, 60));

        un_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                un_txtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(un_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 820, 60));

        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 230, 60));

        newUN.setText("New Username");
        getContentPane().add(newUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 410, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signup.png"))); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void un_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_un_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_un_txtfieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {
            Font fnbold = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/font/Poppins-Bold.ttf"));
            Font fnregular = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/font/Poppins-Regular.ttf"));
            fnbold = fnbold.deriveFont(Font.PLAIN, 30);
            fnregular = fnregular.deriveFont(Font.PLAIN, 30);
            newUN.setFont(fnbold);
            password.setFont(fnbold);
            back2login.setFont(fnregular);
            back2login.setForeground(Color.BLUE);
            un_txtfield.setFont(fnregular);
            pw_txtfield.setFont(fnregular);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_formWindowOpened

    private void back2loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2loginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back2loginMouseEntered

    private void back2loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2loginMouseClicked
        // TODO add your handling code here:
        dispose();
        loginpage ln = new loginpage();
        ln.setVisible(true);
    }//GEN-LAST:event_back2loginMouseClicked

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
    // TODO add your handling code here:
    String username = un_txtfield.getText();
    String password = pw_txtfield.getText();
    
    // Check if any of the text fields are empty
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Both username and password must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Stop execution if any of the fields is empty
    }
    
    //Create the JPA Entity for the user
    Users user = new Users();
    user.setUsername(username);
    user.setPassword(password);
    
    // Insert the user into the db using JPA
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("APPDEVGRP6PU");
    EntityManager em = emf.createEntityManager();
    em.getTransaction().begin();
    em.persist(user);
    em.getTransaction().commit();
    
    em.close();
    emf.close();
    
    // Show a message dialog indicating successful registration
    JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        loginpage ln = new loginpage();
        ln.setVisible(true);
    }//GEN-LAST:event_signupActionPerformed

    private void pw_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_txtfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signuppage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back2login;
    private javax.swing.JLabel background;
    private javax.swing.JLabel newUN;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pw_txtfield;
    private javax.swing.JButton signup;
    private javax.swing.JTextField un_txtfield;
    // End of variables declaration//GEN-END:variables
}
